baseURL = "https://kenji.blog/"
languageCode = "ja"
DefaultContentLanguage = "ja"
title = "kenji.blog"
theme = "PaperMod"
googleAnalytics = "UA-60997585-5"

[params]
    dateFormat= "2006.01.02"
    images = ["twitter_card.jpg"]
    ShowShareButtons = true

[params.label]
    text = "🏠 Home"

[params.homeInfoParams]
    Title = "Hello world! 😊"
    Content = "こんにちは世界。普段考えたことや技術的な小話を短めの記事にメモ代わりで投稿していきます。PaperModというテーマを使っています。"

[[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/kenjinote"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/kenjinote"

[[params.socialIcons]]
    name = "link"
    url = "https://hack.jp"

[[params.socialIcons]]
    name = "email"
    url = "mailto:kenji256@gmai.com"

[[params.socialIcons]]
    name = "KoFi"
    url = "https://ko-fi.com/kenjinote"

[[params.socialIcons]]
    name = "Rss"
    url = "index.xml"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

#[[menu.main]]
#    name = "About"
#    url = "/about"
#    weight = 1

#[[menu.main]]
#    name = "Search"
#    url = "/Search"
#    weight = 2
